spring:
  h2:
    console:
      enabled: true

  jpa:
    show_sql: true
    properties:
      hibernate: dialect=org.hibernate.dialect.MySQL8Dialect
      dialect:
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa

  kafka:
    bootstrapAddress: localhost:9092
    consumer:
      auto-offset-reset: earliest

  #application-secret.yml
  profiles:
    include: secret


springdoc:
   swagger-ui:
     groups-order: desc
     tags-sorter: alpha
     operations-sorter: method
     disable-swagger-default-url: true
     display-request-duration: true
     default-models-expand-depth: 2
     default-model-expand-depth: 2
   api-docs:
     path: /api-docs
   show-actuator: true
   default-consumes-media-type: application/json
   default-produces-media-type: application/json
   writer-with-default-pretty-printer: true
   model-and-view-allowed: true
   paths-to-match:
     - /api/**
