spring:
  h2:
    console:
      enabled: true

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      dialect: dialect=org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${EC2_HOST}:3306/${DATABASE_NAME}
    username: ${EC2_USERNAME}
    password: ${EC2_PASSWORD}


  kafka:
    bootstrapAddress: j10b207.p.ssafy.io:9092 # localhost:9092
    consumer:
      auto-offset-reset: earliest
    topics:
      now-topic: test-topic # alarm-topic
      alarm-topic: alarm-topic

  #application-secret.yml
  profiles:
    include: secret


springdoc:
   swagger-ui:
     groups-order: desc
     tags-sorter: alpha
     operations-sorter: method
     disable-swagger-default-url: true
     display-request-duration: true
     default-models-expand-depth: 2
     default-model-expand-depth: 2
   api-docs:
     path: /api-docs
   show-actuator: true
   default-consumes-media-type: application/json
   default-produces-media-type: application/json
   writer-with-default-pretty-printer: true
   model-and-view-allowed: true
   paths-to-match:
     - /api/**